---
# Dynamic routing—pulls the IP automatically from whatever is in hosts.ini
brane_hub_api: "http://{{ groups['central_hub'][0] }}:30051"

# Dynamically detects system names (linux/darwin) and architectures (x86_64/aarch64)
branectl_url: "https://github.com/BraneFramework/brane/releases/download/nightly/branectl-{{ ansible_system | lower }}-{{ ansible_architecture }}"
brane_cli_url: "https://github.com/BraneFramework/brane/releases/download/nightly/brane-{{ ansible_system | lower }}-{{ ansible_architecture }}"
