# Phase 0 - Uniform Container Engine Baseline Synchronization
- name: Uniform Container Engine Baseline Synchronization
  hosts: all
  become: yes
  roles:
    - { role: docker_setup , tags: ['docker_install'] }

# Pass 1: Local Generation
# Roles run the branectl commands to create all config/db/cert files
- name: Pass 1 - Generate Configurations
  hosts: all
  roles:
    - brane_init   # Create folder structure
    - { role: brane_central, when: "'central_hub' in group_names" , tag: ['central_hub']}  #rane_central
    - { role: brane_workers, when: "'worker_nodes' in group_names", tag: ['worker_nodes']} # brane_workers

# Pass 2: Certificate & Token Exchange
# Only runs after all local config files exist on all nodes
- name: Pass 2 - Distribute & Exchange
  hosts: all
  roles:
  #  - brane_exchange
     - { role: brane_exchange, tags: ['exchange_certs'] }  

# Pass 3: Launch
# Only runs after exchange is complete and trust is established
- name: Pass 3 - Start Services
  hosts: all
  roles:
    - { role: brane_start_services, tags: ['start_services']}

# Pass 5: deploy a user node
#- hosts: user_nodes
#  become: yes
#  roles:
#    - role: brane_user_node
#  when: deploy_demo_node | default(false) | bool

# Pass 4: clean
#- name: Pass 4 - Stop all 
#  hosts: all
#  roles:
#     - role: cleanup
#       tags: ['cleanup']
#  when: cleanup  | default(false) | bool

# Pass 4: deploy pakcags 
# run only after the brane services have started
#- name: Pass 4 - deply packages
#  hosts: brane_central
#  roles:
#    - brane_packagee_deployer , tags: ['package_deployer']}
#  when: ackage_deployer | default(false)  | bool
