---  # site.yml

- name: "Brane — prerequisites on all nodes"
  hosts: all
  become: true
  gather_facts: true
  tags: [prerequisites]
  tasks:
    - name: "Include prerequisites tasks"
      include_role:
        name: brane_deploy
        tasks_from: prerequisites

- name: "Brane — install branectl on all nodes"
  hosts: all
  become: false
  gather_facts: true
  tags: [branectl]
  tasks:
    - name: "Include branectl tasks"
      include_role:
        name: brane_deploy
        tasks_from: branectl

- name: "Brane — install brane cli"
  hosts: all
  become: false
  gather_facts: true
  tags: [branecli]
  tasks:
    - name: "Include branecli tasks"
      include_role:
        name: brane_deploy
        tasks_from: branecli

- name: "Brane — configure & prepare worker nodes"
  hosts: workers
  become: false
  gather_facts: true
  tags: [workers]
  tasks:
    - name: "Include worker tasks"
      include_role:
        name: brane_deploy
        tasks_from: worker

- name: "Brane — configure & prepare central node"
  hosts: central
  become: false
  gather_facts: true
  tags: [central]
  tasks:
    - name: "Include central tasks"
      include_role:
        name: brane_deploy
        tasks_from: central

- name: "Brane — exchange certificates"
  hosts: all
  become: false
  gather_facts: false
  tags: [certs]
  tasks:
    - name: "Include certs tasks"
      include_role:
        name: brane_deploy
        tasks_from: certs

- name: "Brane — start Brane (workers + central)"
  hosts: all
  become: false
  gather_facts: false
  tags: [start]
  tasks:
    - name: "Include start tasks"
      include_role:
        name: brane_deploy
        tasks_from: start

- name: "Brane — smoke test"
  hosts: central
  become: false
  gather_facts: false
  tags: [smoke]
  tasks:
    - name: "Include smoke test tasks"
      include_role:
        name: brane_deploy
        tasks_from: smoke_test

- name: "Brane — remove deployment artefacts for a version change"
  hosts: all_brane_nodes
  become: false
  gather_facts: false
  tags: [cleanup]
  tasks:
    - name: "Include cleanup tasks"
      ansible.builtin.include_role:
        name: brane_deploy
        tasks_from: cleanup
