# roles/brane_init/tasks/main.yml
- name: Create required /tmp/data directory for branectl
  become: yes
  ansible.builtin.file:
    path: /tmp/data
    state: directory
    owner: "{{ ansible_facts['user_id'] }}" 
    #owner: "{{ ansible_user_id }}" # Ensures your user owns it
    mode: '0755'
  loop:
    - /tmp/data
    - /tmp/results

#- name: Create required directory structures
#  ansible.builtin.file:
#    path: "{{ item }}"
#    state: directory
#    mode: '0755'
#  loop:
#    - ~/brane-central/config/certs
#    - ~/brane-central/config/secrets
#    - ~/brane-central/target/release

#- name: Generate configurations (Central)
#  ansible.builtin.command: "branectl generate node central --location {{ location_id }} --hostname {{ central_ip }}"
#  args:
#    chdir: ~/brane-central
#    creates: node.yml
#  when: "'central_hub' in group_names"

#- name: Generate worker certs locally
#  ansible.builtin.command: "branectl generate certs client {{ location_id }} -H {{ node_ip }} -f -p ./config/certs"
#  args:
#    chdir: ~/brane-central
#  when: "'worker_nodes' in group_names"
  
