# roles/brane_user_node/tasks/main.yml
- name: Install prerequisite packages
  ansible.builtin.apt:
    name: 
      - docker-buildx-plugin
      - python3-pip
    state: present
    update_cache: yes

- name: Download and install Brane CLI
  ansible.builtin.get_url:
    url: https://github.com/BraneFramework/brane/releases/download/nightly/brane-linux-x86_64
    dest: /usr/local/bin/brane
    mode: '0755'

- name: Install JupyterHub
  ansible.builtin.pip:
    name: jupyterhub
    executable: pip3

- name: Install JupyterHub notebook
  ansible.builtin.pip:
    name: notebook
    executable: pip3
