---
# tasks file for brane_central


# Step 0: Ensure branectl is installed
- name: Install branectl binary
  become: yes
  ansible.builtin.get_url:
    #url: https://github.com/BraneFramework/brane/releases/download/nightly/branectl-linux-x86_64
    url: "https://github.com/BraneFramework/brane/releases/download/nightly/branectl-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/branectl
    mode: '0755'

# Existing Step A: Directory Structure
- name: Create Brane directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ~/config/certs
    - ~/target/release
    - ~/config/secrets
    - ~/data
    - ~/results

- name: Create unique worker directories on Central Hub to save the certificates
  ansible.builtin.file:
    path: "~/config/certs/{{ hostvars[item]['location_id'] }}"
    state: directory
    mode: '0755'
  loop: "{{ groups['worker_nodes'] }}"
  delegate_to: "{{ groups['central_hub'][0] }}"

# Step B.1: Download core services and auxiliary images [cite: 14]
- name: Download Brane services and auxiliary images
  ansible.builtin.command:
    cmd: "branectl download services {{ item }} -f"
  loop:
    - central
    - auxillary
  when: "'central_hub' in group_names"

# Step B.2: Generate infrastructure configuration [cite: 14]
- name: Generate infrastructure configuration
  ansible.builtin.command:
    cmd: >
          branectl generate infra -f -p ./config/infra.yml
          {% for node in groups['worker_nodes'] %}
          {{ hostvars[node]['ansible_host'] }}
          {% endfor %}
    # cmd: "branectl generate infra -f -p ./config/infra.yml client-node-1:145.100.135.172 client-node-2:145.100.135.241"
  args:
    creates: ./config/infra.yml

# Step B.3: Generate proxy configuration [cite: 14]
- name: Generate proxy configuration
  ansible.builtin.command:
    cmd: "branectl generate proxy -f -p ./config/proxy.yml"
  args:
    creates: ./config/proxy.yml

# Step B.4: Generate central_hub  certificates (ca.pem and server.pem)
- name: Generate central_hub  certificates (ca.pem and server.pem)
  ansible.builtin.command:
    cmd: branectl generate certs server -f -p ~/config/certs/ {{ location_id }}
    #args:
    creates: ./config/certs/ca.pem
  when: inventory_hostname in groups['central_hub']
# =============================================================
# only for debugging
# -------------------------------------------------------------
- name: Generate central_hub certificates
  ansible.builtin.command:
    # Use the absolute path found via 'which'
    cmd: "/usr/local/bin/branectl generate certs server -f -p ~/brane-central/config/certs/ {{ location_id }}"
  register: branectl_output
  ignore_errors: true

- name: Debug Output
  ansible.builtin.debug:
    msg: 
      - "STDOUT: {{ branectl_output.stdout }}"
      - "STDERR: {{ branectl_output.stderr }}"
      - "RETURN CODE: {{ branectl_output.rc }}"
  when: branectl_output.failed

#===========================    
# Step B.5: Generate node configuration [cite: 15]
#=================================================
- name: Generate node configuration
  ansible.builtin.command:
    cmd: "branectl generate node -f central ab-01.uvalight.net"
  args:
    creates: ./node.yml
