---
# roles/brane/tasks/branecli.yml
# Download and install the brane binary (on controler, no sudo).

# create ./local/bin directories
- name: "Control | Create .local/bin directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "0755"
  become: false
  tags: [branecli]

# download brane CLI
- name: "Control | Download brane CLI"
  ansible.builtin.get_url:
    url: "{{ brane_cli_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/brane"
    mode: "0755"
  become: false
  tags: [branecli]

# verify installed brane  CLI
- name: "Control | Verify brane CLI installed"
  ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/brane --version"
  register: brane_version
  changed_when: false
  become: false
  tags: [branecli]

# show version of brane CLI
- name: "brane cli | Show version"
  ansible.builtin.debug:
    msg: "brane version: {{ brane_version.stdout }}"
  tags: [branecli]
