# roles/brane_start_services/tasks/main.yml

- name: Start central services
  ansible.builtin.command: "/usr/local/bin/branectl start central"
  when: "'central_hub' in group_names"

- name: Start worker services
  ansible.builtin.command: "/usr/local/bin/branectl start worker"
  when: "'worker_nodes' in group_names"
  throttle: 1
